### ISSUE TITLE
sftpd not starting

### ISSUE THREAD

**Issue by bchatelard** [scaleway-community/scaleway-torrents#21]
The sftpd service is not launching on startup.

```
$ /usr/sbin/vsftpd
500 OOPS: SSL: cannot load RSA certificate
```

Commenting this lines into /etc/vsftpd.conf seems to fix the issue.
```
#ssl_enable=YES
```

I believe this was introduced by 2aba94462abb5ce5a9dabea141370a0f23187990 (#14)

**Comment by moul** [comment]
Introduced by #14

**Comment by moul** [comment]
cc @brmzkw

**Comment by brmzkw** [comment]
Indeed, it was my fault. I didn't created the SSL certificates required for vsftpd to start. https://github.com/scaleway-community/scaleway-torrents/pull/24 fixes the issue.
