### ISSUE TITLE
Reduce wasted downloaded data

### ISSUE THREAD

**Issue by brmzkw** [scaleway-community/scaleway-torrents#26]
See: https://community.scaleway.com/t/torrents-1-2-0-rtorrent-download-much-wasted-data-up-to-70-wasted-data/1196/16

**Comment by rarbg** [comment]
@brmzkw 
Just update the rtorrent/libtorrent to 0.9.6 where they implemented a new hashing policy

**Comment by brmzkw** [comment]
Unfortunately on Ubuntu [rTorrent](http://packages.ubuntu.com/trusty/rtorrent) is on version 0.9.2-1 and [libtorrent14](http://packages.ubuntu.com/trusty/libtorrent14) on version 0.13.2-1. Do you know if they intend to package newer versions?

**Comment by rarbg** [comment]
Ubuntu's rtorrent/libtorrent are not maintained since 2012/2013 :)
My suggestion to you is to build your own scaleway packages from source

**Comment by brmzkw** [comment]
Note: #27 intends to fix the issue

**Comment by rarbg** [comment]
Did you test if the wasted data is now no longer a big % ?

**Comment by brmzkw** [comment]
No, I didn't. I only reviewed the changes of @QuentinPerez, and made a few comments.

My comment above was just to link the PR here.

**Comment by multun** [comment]
The image migrated to deluge, which does not seem to have the same problem.
