### ISSUE TITLE
Can't delete files

### ISSUE THREAD

**Issue by bnetter** [scaleway-community/scaleway-torrents#28]
We should be able to delete the files somehow, ideally from h5ai.

**Comment by EpocDotFr** [comment]
You also can from the ruTorrent interface. Right click on a torrent > Delete... Then you can choose to only remove the torrent from rtorrent or completely remove the files and the torrent.

**Comment by bnetter** [comment]
I tried that but it didn't work @EpocDotFr.

**Comment by EpocDotFr** [comment]
Any error message?

**Comment by bhanuc** [comment]
Did anyone fix this ?

**Comment by multun** [comment]
The image migrated to deluge, which enables moving and deleting the content of torrents.
if it doesn't work (it does, trust me), you could still ssh to the box and do whatever you want !
