### ISSUE TITLE
500 OOPS: prctl PR_SET_SECCOMP failed

### ISSUE THREAD

**Issue by brmzkw** [scaleway-community/scaleway-torrents#34]
On a fresh install on a C2S instance, FTP connection fail with the following error message:

```
500 OOPS: prctl PR_SET_SECCOMP failed
```
From superuser (http://superuser.com/questions/908024/vsftpd-500-oops-prctl-pr-set-seccomp-failed):

```
It can happen when your kernel does not have CONFIG_SECCOMP_FILTER enabled.
```
and indeed:

```# zcat /proc/config.gz  | grep -i CONFIG_SECCOMPP_FILTER
#```

We could set `seccomp_sandbox=no` in **/etc/vsftpd.conf** but I guess it would be preferable to build the module.

Your thoughts @moul, @QuentinPerez?

**Comment by QuentinPerez** [comment]
`CONFIG_SECCOMP` is now available, the default bootscript has been changed

```console
# zcat  /proc/config.gz | grep CONFIG_SECCOMP_FILTER
CONFIG_SECCOMP_FILTER=y
```

**Comment by brmzkw** [comment]
Can you rebuild the torrents image so I can check everything is ok now?

**Comment by QuentinPerez** [comment]
We don't need to rebuild the image

**Comment by brmzkw** [comment]
yeah indeed, it works fine with the latest (default) bootscript.

Thanks,
