### ISSUE TITLE
Rutorrent client not showing country flag near peers,how to fix?

### ISSUE THREAD

**Issue by Dratas** [scaleway-community/scaleway-torrents#36]
Hello,i have installed torrent app from image hub,everything is working fine,but i dont see country flags near peer.
![peers](https://cloud.githubusercontent.com/assets/18125069/16845146/8ce3bd96-49f0-11e6-88ef-aa5ea76e24f5.PNG)
 how to fix this issue?

**Comment by ArtyumX** [comment]
Have you tried : 
apt-get install php5-geoip ?

**Comment by Dratas** [comment]
installed other way and older version 3.6,it works without any glitches.:)

**Comment by multun** [comment]
It was fixed in 5ba6f9, but does not even make any sense now as the image migrated to deluge.
